title: anuraj.dev
url: "https://anuraj.dev"
baseurl: "/"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /blog/:title/
paginate: 5
paginate_path: "/blog/:num/"
page_excerpts: true
logo: /assets/logo.png
feed:
  posts_limit: 5
  excerpt_only: true
  path: /blog/feed.rss
seo_paginator_message: anuraj.dev | a dotnet developer's technical journal
author:
  twitter: anuraj
twitter:
  username: anuraj
  card: summary_large_image
social:
  name: Anuraj
  links:
    - https://twitter.com/anuraj
    - https://www.linkedin.com/in/anurajp
    - https://github.com/anuraj
compress_html:
  clippings: all
  comments: all
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
